"""add cover_image to categories

Revision ID: 21f3db7cacd0
Revises: add_announcement_table
Create Date: 2025-07-17 20:33:11.768618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f3db7cacd0'
down_revision = 'add_announcement_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_created_at'))
        batch_op.drop_index(batch_op.f('ix_announcement_is_active'))
        batch_op.drop_index(batch_op.f('ix_announcement_order'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_active')
        batch_op.drop_column('cover_image')

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
