"""add cover image to posts

Revision ID: add_cover_image_to_posts
Revises: 99e393d2b25b
Create Date: 2024-05-15 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_cover_image_to_posts'
down_revision = '99e393d2b25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cover_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image')
    # ### end Alembic commands ###