"""update_like_table_for_guest_support

Revision ID: b8d2c11b6d91
Revises: 21f3db7cacd0
Create Date: 2025-07-18 11:22:25.958315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8d2c11b6d91'
down_revision = '21f3db7cacd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_ip', sa.String(length=45), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('unique_guest_post_like', ['guest_ip', 'post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_guest_post_like', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('guest_ip')

    # ### end Alembic commands ###
